version: '3.8'

services:
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  app:
    build:
      context: ./app
    environment:
      OPENBAO_URL: ${OPENBAO_URL}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      OPENBAO_KEY: ${OPENBAO_KEY}
      OPENBAO_TOKEN: ${OPENBAO_TOKEN}
    depends_on:
      - mariadb
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
