version: '3.8'

services:
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testvault
      MYSQL_USER: testvault
      MYSQL_PASSWORD: vaultpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  openbao:
    image: openbao/openbao:latest
    command: server -config=/vault/config/config.hcl
    ports:
      - "8200:8200"
    volumes:
      - ./openbao_data:/vault/file
      - ./openbao/config.hcl:/vault/config/config.hcl:ro
    cap_add:
      - IPC_LOCK

  app:
    build:
      context: ./app
    environment:
        VAULT_ADDR: http://openbao:8200
        VAULT_TOKEN: s.IHYHzZZd0NsoVxvTsJqm4Tmj
    depends_on:
      - mariadb
      - openbao
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
